modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="metaverse"
version="${file.jarVersion}"
displayName="metaverse"
#updateJSONURL="http://myurl.me/"
authors="Redstoneguy129"
description="A mod"

[[dependencies.metaverse]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.metaverse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
